version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./highapp/
    env_file: .env
    depends_on: 
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  gateway:
    build: ./gateway/
    depends_on: 
      - backend
    ports:
      - 8000:80 